language: bash

before_script:
  - git clone https://github.com/sstephenson/bats.git
  - cd bats
  - sudo ./install.sh /usr/local
  - cd ../
  - rm -rf bats

script:
    - make test
    - x=$(git diff HEAD~1..HEAD~1 CHANGELOG.md | wc -l)
    - if (( x == 0 )); then echo "Please update the CHANGELOG.md"; fi
